
  CREATE TABLE "SYSTEM"."PRODUCTS" 
   (	"PRODUCTID" NUMBER(10,0), 
	"SKU" NUMBER(10,0), 
	"IDSKU" VARCHAR2(20 BYTE), 
	"VENDORPRODUCTID" VARCHAR2(20 BYTE), 
	"PRODUCTNAME" VARCHAR2(200 BYTE), 
	"PRODUCTDESCRIPTION" VARCHAR2(255 BYTE), 
	"SUPPLIERID" NUMBER(10,0), 
	"CATEGORYID" NUMBER(10,0), 
	"QUANTITYPERUNIT" NUMBER(10,0), 
	"UNITPRICE" NUMBER(10,2), 
	"MSRP" NUMBER(10,2), 
	"AVAILABLESIZES" VARCHAR2(200 BYTE), 
	"AVAILABLECOLORS" VARCHAR2(200 BYTE), 
	"PRODUCTSIZE" NUMBER(10,0), 
	"COLOR" VARCHAR2(100 BYTE), 
	"DISCOUNT" NUMBER(10,2), 
	"UNITWEIGHT" NUMBER(10,2), 
	"UNITINSTOCK" NUMBER(10,0), 
	"UNITINORDER" NUMBER(10,0), 
	"REORDERLEVEL" VARCHAR2(100 BYTE), 
	"PRODUCTAVAILABLE" VARCHAR2(4 BYTE), 
	"DISCOUNTAVAILABLE" VARCHAR2(20 BYTE), 
	"CURRENTORDER" NUMBER(10,0), 
	"PICTURE" VARCHAR2(100 BYTE), 
	"RANKING" NUMBER(10,0), 
	"NOTE" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
